version: "3.7"

services:
  database: 
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=ignite_api
    volumes: 
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: ignite_api
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links:
      - database
    depends_on: 
      - database
    restart: always

volumes: 
  pgdata: 
    driver: local